volumes:
  beyondmd-data:
    external: true

services:
  static:
    image: nginx
    volumes:
      - ./static/www:/usr/share/nginx/html
    ports:
      - 8080:80

  react:
    build:
      context: ./client
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./client:/app:delegated
      - /node_modules
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true

  django:
    build:
      context: ./server
      dockerfile: ./Dockerfile.dev
    depends_on:
      - postgres
    volumes:
      - ./server:/app
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: postgres://hnrykm:password@postgres:5432/service
      WAIT_HOSTS: postgres:5432
      WAIT_TIMEOUT: 240

  postgres:
    image: postgres:16.0-bullseye
    volumes:
      - beyondmd-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: hnrykm
      POSTGRES_PASSWORD: password
      POSTGRES_DB: beyondmd_db
