volumes:
  beyondmd-data:
    external: true
  pg-admin-bmd:
    external: true

services:
  static:
    image: nginx
    volumes:
      - ./static:/usr/share/nginx/html
    ports:
      - 8080:80

  react:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./client:/app
    ports:
      - 3000:3000
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: '0.0.0.0'

  django:
    build:
      context: ./server
      dockerfile: ./Dockerfile.dev
    depends_on:
      - postgres
    volumes:
      - ./server:/app
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: postgres://hnrykm:password@postgres:5432/service
      WAIT_HOSTS: postgres:5432
      WAIT_TIMEOUT: 240

  postgres:
    build:
      context: data
      dockerfile: Dockerfile.dev
    image: postgres:14.5-bullseye
    volumes:
      - beyondmd-data:/var/lib/postgresql/data
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: hnrykm
      POSTGRES_PASSWORD: password
      POSTGRES_DB: beyondmd_db

  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin-bmd:/var/lib/pgadmin
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: hnrykm@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DISABLE_POSTFIX: 1
