# Generated by Django 4.2.5 on 2023-09-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_date", models.DateField(auto_now=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("birth_year", models.SmallIntegerField()),
                ("is_male", models.BooleanField()),
                ("avatar", models.CharField(max_length=255)),
                ("symptom_1", models.CharField(max_length=100)),
                ("symptom_2", models.CharField(max_length=100)),
                ("symptom_3", models.CharField(max_length=100)),
                ("diagnosis_1", models.CharField(max_length=100)),
                ("diagnosis_2", models.CharField(max_length=100)),
                ("status", models.CharField(default="Examined", max_length=100)),
            ],
        ),
    ]
