# Generated by Django 4.2.5 on 2023-10-05 21:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="record",
            old_name="diagnosis_1",
            new_name="diagnosis",
        ),
        migrations.RemoveField(
            model_name="record",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="record",
            name="diagnosis_2",
        ),
        migrations.RemoveField(
            model_name="record",
            name="status",
        ),
        migrations.RemoveField(
            model_name="record",
            name="symptom_3",
        ),
    ]
