# Generated by Django 4.2.5 on 2023-10-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0002_rename_diagnosis_1_record_diagnosis_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="exam_date",
            field=models.DateField(),
        ),
    ]
