# Generated by Django 4.2.5 on 2023-10-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0003_alter_record_exam_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="diagnosis",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="record",
            name="symptom_1",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="record",
            name="symptom_2",
            field=models.CharField(max_length=255),
        ),
    ]
